'use client';

import { discoverApi, FestivalDiscoveryResponse } from '@/app/lib/api/discover-api';
import { FestivalDiscoveryForm } from '@/components/festival-discovery-form';
import { Logo } from '@/components/logo';
import { RecommendationsList } from '@/components/recommendations-list';
import { RecommendationsLoadingSpinner } from '@/components/recommendations-loading-spinner';
import { UserPreferences } from '@/lib/schemas';
import type { ReactElement } from 'react';
import { useState } from 'react';

/**
 * Main page component for the Music Festival Assistant
 */
export default function HomePage(): ReactElement {
    const [isLoading, setIsLoading] = useState(false);
    const [discoveryResponse, setDiscoveryResponse] = useState<FestivalDiscoveryResponse | null>(null);
    const [error, setError] = useState<string | null>(null);

    /**
     * Handle festival discovery request
     */
    const handleSubmit = async (festivalId: string, userPreferences: UserPreferences): Promise<void> => {
        setIsLoading(true);
        setError(null);

        // scroll to bottom of the page
        if (typeof window !== 'undefined' && 'scrollBy' in window) {
            setTimeout(() => {
                window.scrollBy({ top: 200, behavior: 'smooth' });
            }, 100);
        }

        try {
            const response = await discoverApi.getRecommendations(festivalId, userPreferences);
            if (response.status === 'success' && response.data) {
                setDiscoveryResponse(response.data);
            } else {
                throw new Error('Failed to fetch recommendations. Please try again later.');
            }
        } catch (err) {
            setError(err instanceof Error ? err.message : 'An unexpected error occurred');
        } finally {
            setIsLoading(false);
        }
    };

    const handleChange = (): void => {
        setDiscoveryResponse(null);
        setError(null);
    };

    return (
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-2">
            {/* Hero Section */}
            <div className="text-center p-2 md:p-4 flex flex-col gap-2">
                <h1 className="text-2xl font-bold text-gray-900">Discover Your Next Favorite Artist</h1>
                <p className="text-base text-gray-600 max-w-3xl mx-auto">
                    Choose from our collection of festivals and get personalized artist recommendations based on your music preferences. Never miss out on discovering amazing music again.
                </p>
            </div>

            {/* Discovery Form */}
            <div className="mb-8">
                <FestivalDiscoveryForm onSubmit={handleSubmit} onChange={handleChange} isLoading={isLoading} />
            </div>

            {/* Error Display */}
            {error && (
                <div className="mb-8 p-4 bg-text-destructive/50 border border-destructive rounded-lg">
                    <div className="flex">
                        <div className="flex-shrink-0">
                            <span className="text-destructive">⚠️</span>
                        </div>
                        <div className="ml-3">
                            <h3 className="text-sm font-medium text-destructive">Error</h3>
                            <p className="mt-1 text-sm text-destructive">{error}</p>
                        </div>
                    </div>
                </div>
            )}

            {/* Loading State */}
            {isLoading && (
                <div className="flex justify-center py-12">
                    <RecommendationsLoadingSpinner />
                </div>
            )}

            {/* Results */}
            {discoveryResponse && !isLoading && (
                <div className="animate-fade-in">
                    <RecommendationsList festival={discoveryResponse.festival} recommendations={discoveryResponse.recommendations} />
                </div>
            )}

            {/* Empty State */}
            {!discoveryResponse && !isLoading && !error && (
                <div className="text-center py-12">
                    <div className="text-6xl mb-4">
                        <Logo className="w-16 h-16 mx-auto" size={40} />
                    </div>
                    <h3 className="text-lg font-medium text-gray-900 mb-2">Ready to Discover Amazing Music?</h3>
                    <p className="text-gray-600">Select a festival above and your preferences to get started with personalized recommendations.</p>
                    <p className="text-gray-500 text-sm mt-4">
                        The recommendations are generated by AI based on your preferences and the festival lineup.
                        <br />
                        The recommendations may not be fully accurate.
                        <br />
                        But they are a great way to discover new artists you might love!
                    </p>
                </div>
            )}
        </div>
    );
}
